title: "m-5553 photography"
author:  "m-5553"
baseurl: "" 
url: "https://m-5553.github.io"
author: 
  name : Matija "m-5553"
  email: autumntrees@protonmail.com
license: "https://creativecommons.org/licenses/by-nc/4.0/"

collections:
  books:
    output: true
    permalink: /books/:path/
  blog:
    output: true
    permalink: /blog/:path/

markdown: kramdown

theme:

plugins:
- jekyll-seo-tag